### ISSUE TITLE
[Feat] 클래스룸 생성 api 추가

### ISSUE THREAD

**Issue by SongGwanSeok** [Co-due/Backend-db-server#19]
## 📝 Description
**무엇을?**
- 클래스룸 생성 기능 추가

**왜?**
- 클래스룸 생성하기 위해

## ❗️Todo
- [ ] 클래스룸 도메인 생성
- [ ] 이름 중복 체크
- [ ] 생성 요청을 받아 db에 저장

## ETC
기타사항
